function fig_handle = plot_hw_convergence(results_struct, a, sigma, cds_bps)
% PLOT_HW_CONVERGENCE Generates convergence plots for CVA and Clean/Risky Prices.
%
% INPUTS:
%   results_struct : [Struct] Data generated by run_hw_pricing_amortizing_swap_CVA
%   a              : [Scalar] Calibrated mean reversion speed
%   sigma          : [Scalar] Calibrated short-rate volatility
%   cds_bps        : [Scalar] CDS Spread value in basis points
%
% OUTPUTS:
%   fig_handle     : [Figure] Handle to the generated figure window

    % Extract vector tracks from the data structure
    steps        = results_struct.Steps_Per_Year;
    cva_values   = results_struct.CVA;
    clean_prices = results_struct.Risk_free_Swap_Price;
    risky_prices = results_struct.Risky_Swap_Price;
    
    % Initialize figure environment
    fig_title = sprintf('HW Tree Convergence Analysis - CDS %d bps', cds_bps);
    fig_handle = figure('Name', fig_title, 'Position', [150, 150, 1200, 500]);
    
    % Subplot 1: Credit Value Adjustment (CVA)
    subplot(1, 2, 1);
    plot(steps, cva_values, '-o', 'LineWidth', 1.8, 'MarkerSize', 6, ...
        'MarkerFaceColor', [0 0.4470 0.7410], 'Color', [0 0.4470 0.7410]);
    title(sprintf('CVA Mesh Convergence (CDS = %d bps)', cds_bps));
    xlabel('Time Steps per Year (\Delta t)');
    ylabel('CVA Value (EUR)');
    grid on;
    set(gca, 'GridAlpha', 0.25);
    
    % Subplot 2: Swap Prices Comparison (Risk-Free vs Risky)
    subplot(1, 2, 2);
    % Plot Risk-Free Price (Clean NPV)
    p1 = plot(steps, clean_prices, '-s', 'LineWidth', 1.8, 'MarkerSize', 6, ...
        'MarkerFaceColor', [0.8500 0.3250 0.0980], 'Color', [0.8500 0.3250 0.0980]);
    hold on;
    
    % Plot Risky Price (Risky NPV)
    p2 = plot(steps, risky_prices, '-d', 'LineWidth', 1.8, 'MarkerSize', 6, ...
        'MarkerFaceColor', [0.4660 0.6740 0.1880], 'Color', [0.4660 0.6740 0.1880]);
    
    title('Swap NPV Convergence Comparison');
    xlabel('Time Steps per Year (\Delta t)');
    ylabel('Swap Value (EUR)');
    legend([p1, p2], {'Risk-Free NPV (Clean)', 'Risky NPV'}, 'Location', 'best');
    grid on;
    set(gca, 'GridAlpha', 0.25);
    hold off;
    
    % Global text layout heading
    sgtitle(sprintf('Hull-White Tree Discretization Study (a = %.4f, \\sigma = %.4f)', a, sigma));
end