function fig_handle = plot_hw_convergence(results_const, results_pwc, cds_bps)
% PLOT_HW_CONVERGENCE Generates convergence plots comparing Constant and Piecewise Constant 
% Sigma approaches in HW.
%
% This function plots the Credit Value Adjustment (CVA) and the Clean/Risky 
% Swap prices as a function of the time steps per year, overlaying the 
% Constant Sigma and Piecewise Constant Sigma approaches for comparison.
%
% INPUTS:
%   results_const : [Struct] Data generated by the HW tree using Constant Sigma.
%   results_pwc   : [Struct] Data generated by the HW tree using Piecewise Constant Sigma.
%   cds_bps       : [Scalar] CDS Spread value in basis points (used for titles).
%
% OUTPUTS:
%   fig_handle    : [Figure] Handle to the generated figure window.

    % Extract vector tracks for the Constant Sigma approach
    steps_const = results_const.Steps_Per_Year;
    cva_const   = results_const.CVA;
    clean_const = results_const.Risk_free_Swap_Price;
    risky_const = results_const.Risky_Swap_Price;
    
    % Extract vector tracks for the Piecewise Constant (PWC) Sigma approach
    steps_pwc = results_pwc.Steps_Per_Year;
    cva_pwc   = results_pwc.CVA;
    clean_pwc = results_pwc.Risk_free_Swap_Price;
    risky_pwc = results_pwc.Risky_Swap_Price;
    
    % Initialize the figure environment
    fig_title = sprintf('HW Convergence Analysis - CDS %d bps', cds_bps);
    fig_handle = figure('Name', fig_title, 'Position', [100, 100, 1200, 500]);
    
    % Subplot 1: Credit Value Adjustment (CVA) Convergence
    subplot(1, 2, 1);
    plot(steps_const, cva_const, '-o', 'LineWidth', 1.8, 'Color', [0 0.4470 0.7410], 'DisplayName', 'Constant Sigma');
    hold on;
    % Fixed the missing color attribute here
    plot(steps_pwc, cva_pwc, '-s', 'LineWidth', 1.8, 'Color', [0.8500 0.3250 0.0980], 'DisplayName', 'Piecewise Constant Sigma');
    
    title(sprintf('CVA Mesh Convergence (CDS = %d bps)', cds_bps));
    xlabel('Time Steps per Year (\Delta t)');
    ylabel('CVA Value (EUR)');
    legend('show', 'Location', 'best');
    grid on;
    
    % Subplot 2: Swap Prices Convergence (Risk-Free vs Risky)
    subplot(1, 2, 2);
    % Plot lines for Constant Sigma
    plot(steps_const, clean_const, '--o', 'LineWidth', 1.2, 'Color', [0.4660 0.6740 0.1880], 'DisplayName', 'RF NPV (Constant)');
    hold on;
    plot(steps_const, risky_const, '-o', 'LineWidth', 1.8, 'Color', [0.4940 0.1840 0.5560], 'DisplayName', 'Risky NPV (Constant)');
    
    % Plot lines for Piecewise Constant Sigma
    plot(steps_pwc, clean_pwc, '--x', 'LineWidth', 1.2, 'Color', [0.3010 0.7450 0.9330], 'DisplayName', 'RF NPV (Piecewise Const)');
    plot(steps_pwc, risky_pwc, '-x', 'LineWidth', 1.8, 'Color', [0.6350 0.0780 0.1840], 'DisplayName', 'Risky NPV (Piecewise Const)');
    
    title(sprintf('Swap Prices Convergence (CDS = %d bps)', cds_bps));
    xlabel('Time Steps per Year (\Delta t)');
    ylabel('Swap Value (EUR)');
    legend('show', 'Location', 'best');
    grid on;
end