function fig_handle = plot_hw_convergence(results_struct, cds_bps)
% PLOT_HW_CONVERGENCE Generates convergence plots for the Constant Sigma
% approach in the Hull-White Trinomial Tree model.
%
% INPUTS:
%   results_struct : [Struct] Data generated by run_hw_pricing_amortizing_swap_CVA
%                             containing fields: .Steps_Per_Year, .CVA, 
%                             .Risk_free_Swap_Price, .Risky_Swap_Price
%   cds_bps        : [Scalar] CDS Spread value in basis points (for titles).
%
% OUTPUTS:
%   fig_handle     : [Figure] Handle to the generated figure window.

    % Extract vector tracks from the results structure
    steps        = results_struct.Steps_Per_Year;
    cva_vals     = results_struct.CVA;
    clean_prices = results_struct.Risk_free_Swap_Price;
    risky_prices = results_struct.Risky_Swap_Price;
    
    fig_handle = figure('Color', [1 1 1], 'Position', [100, 100, 1100, 450]);
    
    % SUBPLOT 1: Credit Value Adjustment (CVA) Convergence
    subplot(1, 2, 1);
    plot(steps, cva_vals, '-o', 'LineWidth', 2.0, 'Color', [0 0.4470 0.7410], ...
         'MarkerFaceColor', [0 0.4470 0.7410], 'MarkerSize', 6);
    
    title(sprintf('CVA Mesh Convergence (CDS = %d bps)', cds_bps), ...
          'FontSize', 11, 'FontWeight', 'bold');
    xlabel('Time Steps per Year (\Delta t)', 'FontSize', 10);
    ylabel('CVA Value (EUR)', 'FontSize', 10);
    grid on;
    
    % SUBPLOT 2: Swap Prices Convergence (Risk-Free vs Risky)
    subplot(1, 2, 2);
    plot(steps, clean_prices, '--s', 'LineWidth', 1.5, 'Color', [0.4660 0.6740 0.1880], ...
         'MarkerFaceColor', [0.4660 0.6740 0.1880], 'MarkerSize', 5, 'DisplayName', 'Risk-Free NPV');
    hold on;
    plot(steps, risky_prices, '-d', 'LineWidth', 2.0, 'Color', [0.6350 0.0780 0.1840], ...
         'MarkerFaceColor', [0.6350 0.0780 0.1840], 'MarkerSize', 5, 'DisplayName', 'Risky NPV');
    
    title(sprintf('Swap Valuation Convergence (CDS = %d bps)', cds_bps), ...
          'FontSize', 11, 'FontWeight', 'bold');
    xlabel('Time Steps per Year (\Delta t)', 'FontSize', 10);
    ylabel('Net Present Value (EUR)', 'FontSize', 10);
    legend('show', 'Location', 'east');
    grid on;
    
    sgtitle('Hull-White Trinomial Tree Numeric Convergence Analysis', ...
            'FontSize', 13, 'FontWeight', 'bold');
end