function plot_hw_convergence(results_struct, cds_bps)
% PLOT_HW_CONVERGENCE Generates convergence plots for the Constant Sigma
% approach in the Hull-White Trinomial Tree model.
%
% INPUTS:
%   results_struct : [Struct] Data generated by run_hw_pricing_amortizing_swap_CVA
%                             containing fields: .Steps_Per_Year, .CVA, 
%                             .Risk_free_Swap_Price, .Risky_Swap_Price
%   cds_bps        : [Scalar] CDS Spread value in basis points (for titles).
%

    % Extract vector tracks from the results structure
    steps        = results_struct.Steps_Per_Year;
    cva_vals     = results_struct.CVA;
    clean_prices = results_struct.Risk_free_Swap_Price;
    risky_prices = results_struct.Risky_Swap_Price;
    
    figure;
    colorCVA     = [0, 114, 189] / 255;  
    colorRiskFree = [100, 180, 210] / 255; 
    colorRisky    = [225, 125, 115] / 255;
    
    % SUBPLOT 1: Credit Value Adjustment (CVA) Convergence
    ax1 = subplot(1, 2, 1);
    plot(steps, cva_vals, '-o', 'LineWidth', 2.5, 'Color', colorCVA, ...
         'MarkerFaceColor', 'w', 'MarkerSize', 7);
    
    title(sprintf('CVA Convergence (CDS: %d bps)', cds_bps), 'FontName', 'Times New Roman', 'FontSize', 20, 'FontWeight', 'bold');
    xlabel('Time Steps per Year', 'FontName', 'Times New Roman', 'FontSize', 18, 'FontWeight', 'bold');
    ylabel('CVA Value (EUR)', 'FontName', 'Times New Roman', 'FontSize', 18, 'FontWeight', 'bold');
    set(ax1, 'FontName', 'Times New Roman', 'FontSize', 16, 'Box', 'off', 'XColor', [0.3 0.3 0.3], 'YColor', [0.3 0.3 0.3], 'LineWidth', 1.5);
    grid on; ax1.GridLineStyle = ':'; ax1.GridColor = [0.7 0.7 0.7];
    
    % SUBPLOT 2: Swap Prices Convergence (Risk-Free vs Risky)
    ax2 = subplot(1, 2, 2);
    plot(steps, clean_prices, '--s', 'LineWidth', 2.5, 'Color', colorRiskFree, 'MarkerSize', 6, 'DisplayName', 'Risk-Free NPV');
    hold on;
    plot(steps, risky_prices, '-d', 'LineWidth', 2.5, 'Color', colorRisky, 'MarkerSize', 6, 'DisplayName', 'Risky NPV');
    
    title('Swap Valuation Convergence', 'FontName', 'Times New Roman', 'FontSize', 20, 'FontWeight', 'bold');
    xlabel('Time Steps per Year', 'FontName', 'Times New Roman', 'FontSize', 18, 'FontWeight', 'bold');
    ylabel('NPV (EUR)', 'FontName', 'Times New Roman', 'FontSize', 18, 'FontWeight', 'bold');
    lgd = legend('show', 'Location', 'best');
    lgd.FontName = 'Times New Roman'; lgd.FontSize = 14; lgd.Box = 'on';
    
    set(ax2, 'FontName', 'Times New Roman', 'FontSize', 16, 'Box', 'off', 'XColor', [0.3 0.3 0.3], 'YColor', [0.3 0.3 0.3], 'LineWidth', 1.5);
    grid on; ax2.GridLineStyle = ':'; ax2.GridColor = [0.7 0.7 0.7];
    
    sgtitle(sprintf('Hull-White Numeric Convergence'), ...
            'FontName', 'Times New Roman', 'FontSize', 24, 'FontWeight', 'bold');
end