function tree = fit_hw_tree_ois(settlement, tree)
% FIT_HW_TREE_OIS Calibrates the Hull-White tree to the initial OIS curve via 
% Forward Induction.
%
% This function calculates the deterministic drift adjustment (alpha) at each time step 
% using state prices to perfectly replicate the market discount factors, 
% ensuring an arbitrage-free structure.
%
% INPUTS:
%   settlement : [Scalar] Settlement date t0 (datenum).
%   tree       : [Struct] Uncalibrated tree configuration generated by setup_mhw_tree.
%
% OUTPUTS:
%   tree       : [Struct] Tree data structure containing grid arrays, model parameters, 
%                        discrete branching thresholds, calendar mappings, and deterministic spreads.

    % Extract grid variables from the tree structure
    gridDates = tree.gridDates(:);
    timeGrid  = tree.timeGrid(:);
    nSteps    = tree.nSteps;
    dt        = tree.dt;

    % Extract spatial parameters
    l         = tree.l(:);
    x         = tree.x(:);
    l_max     = tree.l_max;
    mu_hat    = tree.mu_hat;

    % Determine total number of spatial nodes and the index of the center node (x=0)
    nNodes    = length(l);
    idx0      = l_max + 1;

    % Extract the market discounting curve
    discCurve = tree.discountCurve;

    % EXTRACT MARKET DISCOUNT FACTORS P(0, t_i)
    
    % Interpolate market OIS zero rates to find the discount factors for every grid date
    marketDF = get_discount_factor_by_zero_rates_linear_interp( ...
        settlement, gridDates, discCurve.dates, discCurve.discounts);
    
    % Force into a column vector
    marketDF = marketDF(:);

    % Safety check: ensure we have exactly one discount factor per time node
    if length(marketDF) ~= nSteps + 1
        error('marketDF must have length nSteps+1.');
    end

    % TREE GEOMETRY & TRANSITION PROBABILITIES
    
    % Pre-allocate transition destination indices and probability vectors
    destUp  = zeros(nNodes, 1);
    destMid = zeros(nNodes, 1);
    destDn  = zeros(nNodes, 1);

    probUp  = zeros(nNodes, 1);
    probMid = zeros(nNodes, 1);
    probDn  = zeros(nNodes, 1);

    % Compute the drift displacement metric for all nodes simultaneously
    M = mu_hat * l;

    % Define boolean masks for the three branching zones
    idxA = (l > -l_max & l < l_max); % Interior nodes
    idxB = (l == -l_max);            % Lower boundary node
    idxC = (l == l_max);             % Upper boundary node

    % CASE A: Interior nodes (Standard symmetric branching)
    destUp(idxA)  = find(idxA) + 1;
    destMid(idxA) = find(idxA);
    destDn(idxA)  = find(idxA) - 1;

    probUp(idxA)  = 1/6 + 0.5 * (M(idxA).^2 - M(idxA));
    probMid(idxA) = 2/3 - M(idxA).^2;
    probDn(idxA)  = 1/6 + 0.5 * (M(idxA).^2 + M(idxA));

    % CASE B: Lower boundary (Asymmetric upward branching)
    destUp(idxB)  = find(idxB) + 2;
    destMid(idxB) = find(idxB) + 1;
    destDn(idxB)  = find(idxB);

    probUp(idxB)  = 1/6 + 0.5 * (M(idxB).^2 + M(idxB));
    probMid(idxB) = -1/3 - M(idxB).^2 - 2 * M(idxB);
    probDn(idxB)  = 7/6 + 0.5 * (M(idxB).^2 + 3 * M(idxB));

    % CASE C: Upper boundary (Asymmetric downward branching)
    destUp(idxC)  = find(idxC);
    destMid(idxC) = find(idxC) - 1;
    destDn(idxC)  = find(idxC) - 2;

    probUp(idxC)  = 7/6 + 0.5 * (M(idxC).^2 - 3 * M(idxC));
    probMid(idxC) = -1/3 - M(idxC).^2 + 2 * M(idxC);
    probDn(idxC)  = 1/6 + 0.5 * (M(idxC).^2 - M(idxC));

    % Safety checks: verify bounds and probability integrity
    if any(destUp < 1 | destUp > nNodes) || any(destMid < 1 | destMid > nNodes) || any(destDn < 1 | destDn > nNodes)
        error('Transitions out of bounds: check A/B/C branching indices.');
    end

    if any(abs((probUp + probMid + probDn) - 1) > 1e-12)
        error('Transition probabilities do not sum to 1.');
    end

    if any(probUp < -1e-14) || any(probMid < -1e-14) || any(probDn < -1e-14)
        error('Negative probabilities detected in the tree: check l_max and mu_hat.');
    end

    % BUILD SPARSE TRANSITION MATRIX
    
    % We construct a sparse transition matrix Pi such that Pi(j, k) is the
    % probability of moving from node j to node k.
    row_indices = [1:nNodes, 1:nNodes, 1:nNodes]';
    col_indices = [destUp; destMid; destDn];
    prob_values = [probUp; probMid; probDn];
    
    % Pi is a [nNodes x nNodes] matrix.
    TransitionMatrix = sparse(row_indices, col_indices, prob_values, nNodes, nNodes);
   
    % FORWARD INDUCTION 

    % Initialize the state prices matrix (q)
    statePrices = zeros(nNodes, nSteps + 1);
    
    % The probability of being at the center node at t=0 is 1
    statePrices(idx0, 1) = 1.0;

    % Pre-allocate calibration arrays
    alpha      = zeros(nSteps, 1);
    shortRates = zeros(nNodes, nSteps);
    nodeDF     = zeros(nNodes, nSteps);

    for i = 1:nSteps
        % Extract the state prices for the current time step i
        q_i = statePrices(:, i);

        % Calculate alpha to exactly fit the next market discount factor
        numer = sum(q_i .* exp(-x * dt));
        alpha(i) = log(numer / marketDF(i+1)) / dt;

        % Apply the calibrated drift to the stochastic spatial grid
        shortRates(:, i) = x + alpha(i);
        
        % Calculate the local 1-step discount factor at each node
        nodeDF(:, i) = exp(-shortRates(:, i) * dt);

        % Calculate the discounted state price contribution from current nodes
        contrib = q_i .* nodeDF(:, i);

        % Multiply the contribution vector by the transposed transition matrix
        % to distribute the state prices to the destination nodes for step i+1.
        statePrices(:, i+1) = TransitionMatrix' * contrib;
    end

    % Verify calibration precision: sum of state prices at column i must equal marketDF(i)
    modelDF = sum(statePrices, 1)';

    % SAVE RESULTS TO TREE STRUCTURE

    tree.fit.marketDF    = marketDF;
    tree.fit.modelDF     = modelDF;
    tree.fit.absErrDF    = modelDF - marketDF;
    tree.fit.relErrDF    = (modelDF - marketDF) ./ max(marketDF, 1e-16);

    tree.fit.alpha       = alpha;
    tree.fit.shortRates  = shortRates;
    tree.fit.nodeDF      = nodeDF;
    tree.fit.statePrices = statePrices;

    tree.fit.destUp      = destUp;
    tree.fit.destMid     = destMid;
    tree.fit.destDn      = destDn;

    tree.fit.probUp      = probUp;
    tree.fit.probMid     = probMid;
    tree.fit.probDn      = probDn;

    tree.fit.timeGrid    = timeGrid;
    tree.fit.gridDates   = gridDates;
end