function plot_hw_convergence(results_array, cds_bps)
% PLOT_HW_CONVERGENCE Generates convergence plots for the Constant Sigma
% approach in the Hull-White Trinomial Tree model.
%
% INPUTS:
%   results_array  : [Struct] Data generated by run_hw_pricing_amortizing_swap_CVA
%                             containing fields: .Steps_Per_Year, .CVA, 
%                             .Risk_free_Swap_Price, .Risky_Swap_Price
%   cds_bps        : [Scalar] CDS Spread value in basis points (for titles).
%


num_scenarios = length(cds_bps);
colorCVA      = [0, 0.4470, 0.7410];   
colorRiskFree = [0.6, 0.6, 0.6];       
colorRisky    = [0.8500, 0.3250, 0.0980];

figure;

for i = 1:num_scenarios


    % Extract vector tracks from the results structure
    steps        = results_array(i).Steps_Per_Year;
    cva_vals     = results_array(i).CVA;
    clean_prices = results_array(i).Risk_free_Swap_Price;
    risky_prices = results_array(i).Risky_Swap_Price;
    
    % SUBPLOT 1: Credit Value Adjustment (CVA) Convergence
    subplot(2, 2, i*2 - 1);
    plot(steps, cva_vals, '-o', 'LineWidth', 2, 'Color', colorCVA, ...
         'MarkerFaceColor', 'w', 'MarkerSize', 5);
    
    title(sprintf('CVA Convergence (CDS: %d bps)', cds_bps(i)), ...
        'FontSize', 12, 'FontWeight', 'bold');
    xlabel('Time Steps per Year');
    ylabel('CVA Value (EUR)');
    grid on;
    
    % SUBPLOT 2: Swap Prices Convergence (Risk-Free vs Risky)
    subplot(2, 2, i*2);
    plot(steps, clean_prices, '--s', 'LineWidth', 2, 'Color', colorRiskFree, ...
         'MarkerSize', 5, 'DisplayName', 'Risk-Free NPV');
    hold on;
    plot(steps, risky_prices, '-d', 'LineWidth', 2, 'Color', colorRisky, ...
         'MarkerSize', 5, 'DisplayName', 'Risky NPV');
         
    title(sprintf('Swap Valuation Convergence (CDS: %d bps)', cds_bps(i)), ...
        'FontSize', 12, 'FontWeight', 'bold');
    xlabel('Time Steps per Year');
    ylabel('NPV (EUR)');
    legend('Location', 'best');
    grid on;

end

sgtitle('Hull-White Numeric Convergence', 'FontSize', 14, 'FontWeight', 'bold');

end